---
- name: Manage mapping entries
  when: postfix_sender_canonicals | length > 0
  notify:
    - rebuild_sender_canonical_db
    - reload-postfix
  block:
    - name: Prepare mappings to internal variable
      ansible.builtin.set_fact:
        __postfix_mappings: "{{ postfix_sender_canonicals }}"

    - name: Update sender_canonical_map variable
      ansible.builtin.set_fact:
        __postfix_sender_canonical_map: "hash:{{ __postfix_sender_canonical_path }}"

    - name: "Manage entries in {{ __postfix_sender_canonical_path }}"
      ansible.builtin.template:
        src: "mapfile.j2"
        dest: "{{ __postfix_sender_canonical_path }}"
        mode: 0644

- name: Remove mapping files
  when: postfix_sender_canonicals | length == 0
  notify:
    - reload-postfix
  block:
    - name: Remove map file
      ansible.builtin.file:
        path: "{{ __postfix_sender_canonical_path }}"
        state: absent

    - name: Remove db file
      ansible.builtin.file:
        path: "{{ __postfix_sender_canonical_path }}.db"
        state: absent
