---
- name: Check for correct platform version
  ansible.builtin.assert:
    that:
      ansible_distribution_version is version('20.04', '==')

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install postfix
  ansible.builtin.package:
    name: postfix
    state: present

- name: Start and enable postfix service
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
