---
# It's sufficient to only remove the packages. The service gets automatically
# stopped and removed from systemd.
- name: Remove postfix from system
  ansible.builtin.dnf:
    name: "{{ postfix_packages }}"
    state: "absent"
    autoremove: true
  when: ansible_distribution_version is version('8', '>=')

- name: Remove postfix from system
  ansible.builtin.yum:
    name: "{{ postfix_packages }}"
    state: "absent"
    autoremove: true
  when: ansible_distribution_version is version('7', '==')
