---
- name: Rebuild alias database
  ansible.builtin.command:
    cmd: postalias "{{ postfix_alias_path }}"
  changed_when: false
  listen: rebuild_aliases_db

# Restart postfix service
- name: Restart postfix service
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: "{{ postfix_restart_state }}"
  listen: "restart-postifx"
  when: postfix_state | default('started') == 'started'
