---
- name: Rebuild alias database
  ansible.builtin.command:
    cmd: postalias "{{ postfix_alias_path }}"
  changed_when: yes
  listen: rebuild_aliases_db

- name: Rebuild sender_canonical database
  ansible.builtin.command:
    cmd: postmap "{{ __postfix_sender_canonical_path }}"
  changed_when: yes
  listen: rebuild_sender_canonical_db

# Restart postfix service
- name: Restart postfix service
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: "{{ postfix_restart_state }}"
  listen: "restart-postifx"
  when: postfix_state | default('started') == 'started'

- name: Reload postfix service
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: "reloaded"
  listen: "reload-postfix"
  when: postfix_state | default('started') == 'started'
