---
- name: Converge to a Postfix server that has the role defaults set.
  hosts: all

  tasks:
    - name: "Include unibe_idsys.postfix"
      ansible.builtin.include_role:
        name: "unibe_idsys.postfix"
