---
- name: Verify the Postfix server converged to the role defaults.
  hosts: all
  gather_facts: false

  tasks:
    - name: Option inet_interfaces defaults to localhost
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^inet_interfaces = localhost"
        state: present
      check_mode: true
      register: inet_interfaces
      failed_when: inet_interfaces is changed

    - name: Option inet_protocols defaults to all
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^inet_protocols = all"
        state: present
      check_mode: true
      register: inet_protocols
      failed_when: inet_protocols is changed

    - name: No relay host is set
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^relayhost ="
        state: absent
      check_mode: true
      register: relayhost
      failed_when: relayhost is changed

    - name: No mail alias for user root
      ansible.builtin.lineinfile:
        path: /etc/aliases
        regexp: "^root:"
        state: absent
      check_mode: true
      register: aliases
      failed_when: aliases is changed

    - name: Postfix service is running
      ansible.builtin.wait_for:
        port: 25
        timeout: 30
      register: port_check
      failed_when: port_check.failed
