---
- name: Converge to a removed root mail alias
  hosts: all

  tasks:
    - name: "Set some aliases..."
      ansible.builtin.include_role:
        name: "unibeid.postfix"
      vars:
        postfix_alias_map:
          root: another-user@test.com

    - name: "... and remove them again"
      ansible.builtin.include_role:
        name: "unibeid.postfix"
      vars:
        postfix_alias_map:
          root: undef
